/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Levels;

import AllGames.GameSelection;
import Database.DBFetchDataEmojiGame;
import Database.DBFetchDataMemoryGame;
import GUI_SmileGame.*;
import Database.DBFetchDataSmileGame;
import GUI_EmojiGame.EmojiGame_Main;
import GUI_MemoryGame.MemoryGame_Main;
import javax.swing.ImageIcon;

/**
 *
 * @author dinithi
 */
public class Level3unlocked extends javax.swing.JFrame {
    DBFetchDataSmileGame data;
    DBFetchDataEmojiGame data1;
    DBFetchDataMemoryGame data2;
    public String game;

    /**
     * Creates new form Level
     */
    public Level3unlocked() {
        initComponents();
        ImageIcon ii = new ImageIcon("gamepictures/level2unlocked.png");
        level_background.setIcon(ii);
        ImageIcon ii1 = new ImageIcon("gamepictures/level1.png");
        btn_Level1.setIcon(ii1);
        ImageIcon ii3 = new ImageIcon("gamepictures/level2.png");
        btn_Level2.setIcon(ii3);
        ImageIcon ii4 = new ImageIcon("gamepictures/level3.png");
        btn_Level3.setIcon(ii4);
        ImageIcon ii2 = new ImageIcon("gamepictures/Level_btn_back.png");
        back_btn.setIcon(ii2);
        data = new DBFetchDataSmileGame();
        data1 = new DBFetchDataEmojiGame();
        data2 = new DBFetchDataMemoryGame();
    }
/**
 * Redirect function to redirect to game selected based on selected level
 * @param game
 * @param currentlevel 
 */
public void redirect(String game, int currentlevel) {
        switch (game) {
            case "SmileGame": {
                data.updatecurrentlevel(lbluser.getText(), currentlevel);
                dispose();
                SmilePuzzleGame_Main eg = new SmilePuzzleGame_Main();
                eg.lableusersmilegame1.setText(lbluser.getText());
                eg.setVisible(true);
                break;
            }
            case "EmojiGame": {
                data1.updatecurrentlevel(lbluser.getText(), currentlevel);
                dispose();
                EmojiGame_Main eg = new EmojiGame_Main();
                eg.lableuseremojigame1.setText(lbluser.getText());
                eg.setVisible(true);
                break;
            }
            case "MemoryGame": {
                data2.updatecurrentlevel(lbluser.getText(), currentlevel);
                dispose();
                //EmojiGame1 eg=new EmojiGame1();
                MemoryGame_Main eg = new MemoryGame_Main();
                eg.lableusermemorygame1.setText(lbluser.getText());
                eg.setVisible(true);
                break;
            }
            default:
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Level1 = new javax.swing.JButton();
        btn_Level2 = new javax.swing.JButton();
        btn_Level3 = new javax.swing.JButton();
        lbluser = new javax.swing.JLabel();
        lblcoins = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        level_background = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Level1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Level1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 170, 180));

        btn_Level2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Level2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Level2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 170, 190));

        btn_Level3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Level3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Level3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 170, 170));

        lbluser.setFont(new java.awt.Font("Malayalam MN", 0, 36)); // NOI18N
        jPanel1.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 130, 60));

        lblcoins.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        jPanel1.add(lblcoins, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 120, 30));

        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 80));
        jPanel1.add(level_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));

        jButton4.setIcon(new javax.swing.ImageIcon("/Users/dinithi/Desktop/3rd Year 1st Semester/CIS/Assignment/gamepictures/Level_btn_back.png")); // NOI18N
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 170, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Level1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Level1ActionPerformed
        /**
         * Based on game selected redirect to game GUI Update current level user
         * selected to play(Level 1)
         */
        redirect(game, 1);
    }//GEN-LAST:event_btn_Level1ActionPerformed

    private void btn_Level2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Level2ActionPerformed
        // TODO add your handling code here:
         /**
         * Based on game selected redirect to game GUI Update current level user
         * selected to play(Level 2)
         */
        redirect(game, 2);
     
    }//GEN-LAST:event_btn_Level2ActionPerformed

    private void btn_Level3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Level3ActionPerformed
        // TODO add your handling code here:
        /**
         * Based on game selected redirect to game GUI Update current level user
         * selected to play(Level 1)
         */
        redirect(game, 3);
    }//GEN-LAST:event_btn_Level3ActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        GameSelection gs=new GameSelection();
        gs.lableuser.setText(lbluser.getText());
        gs.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level3unlocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level3unlocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level3unlocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level3unlocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level3unlocked().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton btn_Level1;
    private javax.swing.JButton btn_Level2;
    private javax.swing.JButton btn_Level3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblcoins;
    public javax.swing.JLabel lbluser;
    private javax.swing.JLabel level_background;
    // End of variables declaration//GEN-END:variables
}
