/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_UserValidation;

import Database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import AllGames.GameSelection;
import Start_GUI.Start2;
import javax.swing.ImageIcon;

/**
 *
 * @author dinithi
 */
public class Login extends javax.swing.JFrame {
DBConnection db;
Connection con;
PreparedStatement preparedStatement;
ResultSet res;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        ImageIcon ii = new ImageIcon("gamepictures/LOGIN.png");
        loginbackground.setIcon(ii);
        ImageIcon ii1 = new ImageIcon("gamepictures/Validating_User/back_btn2.png");
        back_btn.setIcon(ii1);
        
        db = new DBConnection();
        con = db.getConnection();

        JOptionPane.showMessageDialog(rootPane, "con: " + con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        loginbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(213, 123, 175));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 270, 60));

        jLabel2.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel2.setText("Password");
        jLabel2.setAutoscrolls(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, 40));

        txtpassword.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        txtpassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 270, 60));

        jLabel3.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel3.setText("UserName");
        jLabel3.setAutoscrolls(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 170, 40));

        btn_login.setText("GO");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 160, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 400, 390));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 776));

        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 60));
        getContentPane().add(loginbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1320, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(rootPane, "con:" + con);
        /**
         * Getting username entered from JTextField
         */
        String username = txtUsername.getText();
         JOptionPane.showMessageDialog(rootPane, username);
         /**
         * Getting password entered from JTextField
         */
        String password = String.valueOf(txtpassword.getPassword());

        try {
            /**SQL Statement to get 
             * @return 
             */
            preparedStatement = con.prepareStatement("SELECT * FROM `users` WHERE `username`=? and `password`=? ");

            preparedStatement.setString(1, username);
            preparedStatement.setString(2, password);

            // preparedStatement.setString(2, password);
            res = preparedStatement.executeQuery();
            if (res.next()) {
                
                JOptionPane.showMessageDialog(rootPane, "Successful Login!!!");
                /**
                 * Dispose current JFrame Form
                 */
                dispose();
                /**
                 * Redirect to Game Selection JFrame Form
                 */
                GameSelection gs = new GameSelection();
                gs.lableuser.setText(username);
                gs.setVisible(true);

            } else {
                /**
                 * If username or password do not match with data stored in database
                 * Alerts user
                 */
                JOptionPane.showMessageDialog(rootPane, "Username or Password is incorrect");
            }

            //JOptionPane.showMessageDialog(rootPane, "result: "+res.getString(1));
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

       
        
    

    }//GEN-LAST:event_btn_loginActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        /**
         * When User want to go back to Start Page
         * Dispose current JFrame Form and redirect to Start Page
         */
        dispose();
        Start2 s = new Start2();
        s.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginbackground;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
