/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_UserValidation;

/**
 *
 * @author dinithi
 */
import Code_SmileGame.*;
import Database.DBConnection;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

public class SignUp_TEST extends javax.swing.JFrame {
    //UserLinkedList details;
    DBConnection db;
    Connection con;
    ResultSet res;
    Boolean existinguser,checked;
    
    PreparedStatement preparedStatement,preparedStatement2,preparedStatement3,preparedStatement4,preparedStatement5;
    

    /**
     * Creates new form SignUp
     */
    public SignUp_TEST() {
        initComponents();
        ImageIcon ii = new ImageIcon("gamepictures/Sign Up.png");
        signup_background.setIcon(ii);
        ImageIcon ii1 = new ImageIcon("gamepictures/buttongui Medium.jpeg");
        gobtn.setIcon(ii1);
        
         db=new DBConnection();
         con=db.getConnection();
         JOptionPane.showMessageDialog(rootPane, "con: "+con);
         
        
        
       
        
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGender = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        rdfemale = new javax.swing.JRadioButton();
        rdmale = new javax.swing.JRadioButton();
        txtusername = new javax.swing.JTextField();
        txtpwd = new javax.swing.JPasswordField();
        txtcpwd = new javax.swing.JPasswordField();
        gobtn = new javax.swing.JButton();
        DateBday = new com.toedter.calendar.JDateChooser();
        signup_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1345, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 939, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 813, -1, -1));

        jLabel1.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel1.setText("Confirm Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 290, 70));

        jLabel3.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 210, 70));

        jLabel2.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel2.setText("Full Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 180, 90));

        jLabel4.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel4.setText("BirthDay");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 180, 90));

        jLabel5.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel5.setText("UserName");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 180, 70));

        jLabel7.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 180, 60));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 310, 60));

        btnGroupGender.add(rdfemale);
        rdfemale.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        rdfemale.setText("Female");
        getContentPane().add(rdfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 120, 50));

        btnGroupGender.add(rdmale);
        rdmale.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        rdmale.setText("Male");
        getContentPane().add(rdmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 190, 50));
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 310, 60));
        getContentPane().add(txtpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 310, 60));
        getContentPane().add(txtcpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 310, 60));

        gobtn.setText("jButton2");
        gobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobtnActionPerformed(evt);
            }
        });
        getContentPane().add(gobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 250, 110));
        getContentPane().add(DateBday, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 310, 60));
        getContentPane().add(signup_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -35, 1350, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobtnActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(rootPane, "con:"+con);
        /*
         * Retrieving Player details from textfields,radio buttons,calender
        */
        String name=txtname.getText();
        String bday=((JTextField)DateBday.getDateEditor().getUiComponent()).getText();
        String gender;
        String pwd=String.valueOf(txtpwd.getPassword());
        String c_pwd=String.valueOf(txtcpwd.getPassword());
        /*
        *Getting the selected gender
        */
         if(rdfemale.isSelected())
               {
                    gender="female";    
               }
               else{
                    gender="male";
               }
         
        try {
            /*
                *Checking if player already exits in database.
             */
            preparedStatement4 = con.prepareStatement("SELECT * FROM `users` WHERE `username`=? ");
            preparedStatement4.setString(1,txtusername.getText());
            res = preparedStatement4.executeQuery();
            existinguser = res.next();
            //JOptionPane.showMessageDialog(rootPane, "EXIT NEXT"+existinguser);

            checked=existinguser;
            //JOptionPane.showMessageDialog(rootPane, "EXIT NEXT"+checked);
            /*
            *Checks if text fields values are null adn checks if username already exit.
            */
            if (checked==true || name.equals("") || bday.equals("") || gender.equals("") || pwd.equals("") || c_pwd.equals("")) {
              //  JOptionPane.showMessageDialog(rootPane, "Please enter the value to the empty field ");
                if (checked==true) {
                    JOptionPane.showMessageDialog(rootPane, "UserName Already Exits.Please enter a new username");

                }

            }
               else{
                   
               /*
               * Inserting new Player's details here.
               */
               preparedStatement=con.prepareStatement("INSERT INTO `users`(`fullname`, `birthdate`, `gender`, `username`, `password`, `c_password`) VALUES (?,?,?,?,?,?)");
               preparedStatement.setString(1,txtname.getText());
               preparedStatement.setString(2,bday);
               preparedStatement.setString(3,gender);
               preparedStatement.setString(4,txtusername.getText());
               
               /*
               * Inserting new Player's Game status for EmojiGame.
               */
               preparedStatement2=con.prepareStatement("INSERT INTO `EmojiGame`(`username`, `score`, `levelachieved`, `coins`, `current level`) VALUES (?,?,?,?,?)");
               int score=0,level=1,coins=0,currentlevel=0;
               preparedStatement2.setString(1,txtusername.getText());
               preparedStatement2.setInt(2,score);
               preparedStatement2.setInt(3,level);
               preparedStatement2.setInt(4,coins);
               preparedStatement2.setInt(5,currentlevel);
               /*
               * Inserting new Player's Game status for SmileGame.
               */
               preparedStatement3=con.prepareStatement("INSERT INTO `SmileGame`(`username`, `score`, `levelachieved`, `coins`, `current level`) VALUES (?,?,?,?,?)");
               int score1=0,level1=1,coins1=0,currentlevel1=0;
               preparedStatement3.setString(1,txtusername.getText());
               preparedStatement3.setInt(2,score1);
               preparedStatement3.setInt(3,level1);
               preparedStatement3.setInt(4,coins1);
               preparedStatement3.setInt(5,currentlevel1);
                /*
               * Inserting new Player's Game status for MemoryGame.
               */
               preparedStatement5=con.prepareStatement("INSERT INTO `MemoryGame`(`username`, `score`, `levelachieved`, `coins`, `current level`) VALUES (?,?,?,?,?)");
               int score2=0,level2=1,coins2=0,currentlevel2=0;
               preparedStatement5.setString(1,txtusername.getText());
               preparedStatement5.setInt(2,score2);
               preparedStatement5.setInt(3,level2);
               preparedStatement5.setInt(4,coins2);
               preparedStatement5.setInt(5,currentlevel2);
               /*
               *Checks if password and confirm password is same
               */
               if(pwd.equals(c_pwd)){
                    //JOptionPane.showMessageDialog(rootPane, "same");
                    preparedStatement.setString(5,pwd);
                    preparedStatement.setString(6,c_pwd);
                    
                    }
               else{
                   JOptionPane.showMessageDialog(rootPane, "Please enter  same password for confirm password");
               }
               
               /*
               *Executing the Sql Statements
               */
               preparedStatement.executeUpdate();
               preparedStatement2.executeUpdate();
               preparedStatement3.executeUpdate();
               preparedStatement5.executeUpdate();
               JOptionPane.showMessageDialog(rootPane, "Successfully added data!!");
                /*
                *Redirecting to login Page
                */
                dispose();
                Login l=new Login();
                l.setVisible(true);

            }
        } catch (SQLException ex) {
            Logger.getLogger(SignUp_TEST.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "NOT added data!!");

        }
        
        
        
       
    }//GEN-LAST:event_gobtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp_TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp_TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp_TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp_TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp_TEST().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateBday;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.JButton gobtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rdfemale;
    private javax.swing.JRadioButton rdmale;
    private javax.swing.JLabel signup_background;
    private javax.swing.JPasswordField txtcpwd;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpwd;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
