/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_EmojiGame;


import AllGames.GameSelection;
import javax.swing.JOptionPane;
import Database.*;
import Levels.AllLevelunlocked;
import Levels.Level1unlocked;
import Levels.Level2unlocked;
import Levels.Level3unlocked;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Logger;

/**
 *
 * @author dinithi
 */
public class FailedGameEmoji extends javax.swing.JFrame {
    public String user;
    int level,coins;
    DBConnection db;
    Connection con;
    ResultSet Level,Coins;
    DBFetchDataSmileGame data;

    /**
     * Creates new form FailedGame
     */
    public FailedGameEmoji() {
        initComponents();
        db=new DBConnection();
        con=db.getConnection();
        /*
        *Fetch data from SmileGame Table
        */
        data=new DBFetchDataSmileGame();
        coins=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        gameoption = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("/Users/dinithi/Desktop/3rd Year 1st Semester/CIS/Assignment/gamepictures/retry.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 550, 130, 140));

        gameoption.setIcon(new javax.swing.ImageIcon("/Users/dinithi/Desktop/3rd Year 1st Semester/CIS/Assignment/gamepictures/gameoption.png")); // NOI18N
        gameoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameoptionActionPerformed(evt);
            }
        });
        jPanel1.add(gameoption, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 140, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/dinithi/Desktop/3rd Year 1st Semester/CIS/Assignment/gamepictures/failed.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1370, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            
             /**
             * Get level currently achieved by user from database for Smile Game
             */
            Level = data.getlevel(user);

            if (Level.next()) {
                level = Level.getInt("levelachieved");
                JOptionPane.showMessageDialog(rootPane, "level: " + level);
                JOptionPane.showMessageDialog(rootPane, "gone");
            }
            /**
             * Get coins currently earned by user from database for Smile Game
             */
            Coins = data.getcoins(user);
            if (Coins.next()) {
                coins = Coins.getInt("coins");
                /**
                 * Check JOptionPane.showMessageDialog(rootPane, "coins: " +
                 * coins);
                 */

            }
            
             dispose();
            String game = "EmojiGame";
            switch (level) {
                /**
                 * If Level achieved is 1
                 */
                case 1: {

                    Level1unlocked l2 = new Level1unlocked();
                    l2.lbluser.setText(user);
                    l2.lblcoins.setText("" + coins);
                    l2.game = game;
                    l2.setVisible(true);
                    break;
                }
                /**
                 * If Level achieved is 2
                 */
                case 2: {
                    Level2unlocked l2 = new Level2unlocked();
                    l2.lbluser.setText(user);
                    l2.lblcoins.setText("" + coins);
                    l2.game = game;
                    l2.setVisible(true);
                    break;
                }
                /**
                 * If Level achieved is 3
                 */
                case 3: {
                    Level3unlocked l2 = new Level3unlocked();
                    l2.lbluser.setText(user);
                    l2.lblcoins.setText("" + coins);
                    l2.game = game;
                    l2.setVisible(true);
                    break;
                }
                /**
                 * If Level achieved is 4
                 */
                default: {
                    AllLevelunlocked l2 = new AllLevelunlocked();
                    l2.lbluser.setText(user);
                    l2.lblcoins.setText("" + coins);
                    l2.game = game;
                    l2.setVisible(true);
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FailedGameEmoji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void gameoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameoptionActionPerformed
        // TODO add your handling code here:
        dispose();
        GameSelection gs=new GameSelection();
        gs.lableuser.setText(user);
        gs.setVisible(true);
        
    }//GEN-LAST:event_gameoptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FailedGameEmoji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FailedGameEmoji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FailedGameEmoji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FailedGameEmoji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FailedGameEmoji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gameoption;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
